### ISSUE TITLE
(soundness regression) `static mut` could be avoided.

### ISSUE THREAD

**Issue by eddyb** [rust-lang-nursery/lazy-static.rs#117]
At least for `inline_lazy`, the `Option<T>` can be wrapped in `Cell`, needing only:
```rust
unsafe impl<T: Sync> Sync for Lazy<T> {}
```
Then we can just have a regular `static` and `get` can take `&'static self` *safely*.

**EDIT**: As noted below (https://github.com/rust-lang-nursery/lazy-static.rs/issues/117#issuecomment-415454944), the use of `&'static mut Lazy<T>` is unsound.
Also, the `impl` above exists already, UB was introduced by regression at https://github.com/rust-lang-nursery/lazy-static.rs/commit/a308da1d1da7660a9577979c64bb30f0ed0700f7.

cc @anp @RalfJung

**Comment by RalfJung** [comment]
How is an `unsafe impl Sync` any better than a `static mut`?

**Comment by eddyb** [comment]
Because it's provably correct (it only depends on `Lazy::get`'s body) and it makes uses safe.

Right now uses of `Lazy` are unsafe and have to be wrapped, which moves the hazards outside of the module. E.g. today for a reentrant `Lazy::get` you end up with the same `&'static mut Lazy<T>` twice in the call stack, and `miri` with a proper check would scream "UB".

**Comment by eddyb** [comment]
Just proves once more that `static mut` is an unusable mis-feature that creates UB left and right.

**Comment by eddyb** [comment]
Wait, it already has:
```rust
unsafe impl<T: Sync> Sync for Lazy<T> {}
```
What happened here?!

**Comment by RalfJung** [comment]
I find it easier to reason about concurrency :P

> Two Lazy::get on the same callstack with same self address is UB, right?

The question is how long the references live. But given that the outer frame has a reference that's live before and after the reentrant call -- yes, this is UB.

**Comment by KodrAus** [comment]
Ok, so if I'm following this we'll avoid this problem by pushing mutability inside the `Lazy` through a `Cell` and relying on `Once`'s thwarting of attempted re-entrancy to set the value and preventing multiple live mutable references?

**Comment by eddyb** [comment]
@KodrAus Yupp, ignoring the existence references, the current code's memory *accesses* are fine because of the `Once`, all we need to do is avoid `&mut` and use `Cell` instead.
