### ISSUE TITLE
`cargo test` failed after I created a variable with `lazy_static!`.

### ISSUE THREAD

**Issue by hxingpax** [rust-lang-nursery/lazy-static.rs#118]
Every test case involved with the `lazy_static!` variable are poisioned and failed.

How to avoid such a situation.

**Comment by KodrAus** [comment]
@hxingpax The `lazy_static!` can get poisoned if it panics during initialization. Since test cases are all executed in a single runtime all test cases will observe the same `lazy_static!`.

**Comment by hxingpax** [comment]
Thanks, I removed that one. Now I go with lazy_static very carefully.

**Comment by KodrAus** [comment]
@hxingpax Yeh, there are definitely some pitfalls like this to be careful of with global state like `lazy_static`.

If you are hitting a panic somewhere in initialization though one of your tests should have a more descriptive error message that first caused the failure.
