### ISSUE TITLE
Remove "nightly" feature

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang-nursery/lazy-static.rs#136]
I believe it is dead code now? Somewhere in the switching from heap to inline-only it became redundant, it looks like.

**Comment by KodrAus** [comment]
Thanks for the suggestion @Ericson2314! This seems reasonable to me, since the `nightly` feature isn't considered stable.

Would you like to submit a PR?

**Comment by Ericson2314** [comment]
I'm a bit swamped with other things (and don't use travis much myself). Just was reading this again and noticed.

**Comment by KodrAus** [comment]
Ah no worries :+1: If anybody would like to contribute this it'd be much appreciated!

**Comment by Ericson2314** [comment]
If there was just that one line, I would have done it myself :). I think what's left is:
 - [ ] https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/.travis.yml the nightly special-casing is probably not needed
 - [ ] https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/appveyor.yml#L55-L61 same question
 - [ ] https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/src/lib.rs#L95-L96 comments about nightly feature

**Comment by KodrAus** [comment]
Ah thanks! I thought we'd already removed the `nightly` feature from CI but didn't actually check.

I'll chase up these extra bits.
