### ISSUE TITLE
help newbie

### ISSUE THREAD

**Issue by AlbanMinassian** [rust-lang-nursery/lazy-static.rs#137]
i try to set global this examples https://doc.rust-lang.org/1.30.0/book/second-edition/ch17-02-trait-objects.html with lazy_statyc

```rust
pub trait Draw {
    fn draw(&self);
}
pub struct Screen<T: Draw> {
    pub components: Vec<T>,
}
impl<T> Screen<T>
    where T: Draw {
    pub fn run(&self) {
        for component in self.components.iter() {
            component.draw();
        }
    }
}

lazy_static! {
  static ref EXAMPLE: Screen = Screen{ components: vec![] };
}
```
and i have this error

```console
120 |     static ref EXAMPLE: Screen = Screen{ components: vec![] };
    |                         ^^^^^^ expected 1 type argument
```

i don't understand which argument is expected
Can you help me ?
Alban

**Comment by KodrAus** [comment]
Hi @AlbanMinassian :wave:

The problem here is that Rust can't figure out what type to use for `T` in `Screen{ components: vec![] }`.

Is there a specific type you want to store in that list for `EXAMPLE`, or do you want to store any arbitrary type that implements `Draw`?

**Comment by KodrAus** [comment]
It's been a little while now so I'll go ahead and close this one.

If you run into any more trouble with Rust please feel free to reach out [on one of the community channels](https://www.rust-lang.org/community).
