### ISSUE TITLE
spin-rs no longer maintained (dependency)

### ISSUE THREAD

**Issue by briansmith** [rust-lang-nursery/lazy-static.rs#163]
Quoting @bluejekyll at https://github.com/briansmith/ring/issues/921:

> https://rustsec.org/advisories/RUSTSEC-2019-0031
>
> The spin dependency is no longer maintained it appears. This causes cargo audit to fail on downstream projects. I haven't had a chance to look into potential fixes.

Some (probably many) projects have a `cargo audit --deny-warnings` job that will now fail if they depend on lazy-static.

**Comment by GuillaumeDIDIER** [comment]
@phil-opp has developped https://crates.io/crates/spinning_top as a replacement for spin for his rust-os-dev work. Might be of use for this.

**Comment by gendx** [comment]
> @phil-opp has developped https://crates.io/crates/spinning_top as a replacement for spin for his rust-os-dev work. Might be of use for this.

+1 to `spinning_top`. What do you think about it as a replacement?

**Comment by haraldh** [comment]
Maybe also to consider: https://github.com/4lDO2/spinning-rs

**Comment by zesterer** [comment]
FYI, `spin-rs` is now maintained again.

**Comment by tarcieri** [comment]
This PR should hopefully prevent `spin` from being reported as unmaintained:

https://github.com/RustSec/advisory-db/pull/424

**Comment by KodrAus** [comment]
Now that `spin-rs` is back under active maintenance Ithink we can close thisone.

Thanks all!
