### ISSUE TITLE
Update to spin 0.7 for a more performant spinlock

### ISSUE THREAD

**Issue by zesterer** [rust-lang-nursery/lazy-static.rs#181]
A lot of improvements were made for spin 0.7, one of which was the relaxing of unnecessarily strict ordering guarantees. The changes should improve performance of the no-std version of this crate considerably.

**Comment by KodrAus** [comment]
We'd welcome a PR updating `spin` to the latest version!

**Comment by zesterer** [comment]
I'll do so if I find some time over the next few days.

**Comment by ColinFinck** [comment]
Looks like #182 has been merged and this issue can be closed? (sorry, I have no permissions to do that myself)

**Comment by zesterer** [comment]
It might be worth upgrading to `0.9`. For the purpose of this crate, an advantage is that it places the crates (many) features behind feature flags (although you'll need to disable the default ones), reducing unnecessary compilation work.

**Comment by KodrAus** [comment]
We've merged #193 that bumps the `spin` crate to `0.9`. I'll need to get permissions sorted before we can publish a release but will try get on top of that.
