### ISSUE TITLE
[Question]: Why does crate.io have newer versions than in this repository?

### ISSUE THREAD

**Issue by dclong** [rust-lang-nursery/lazy-static.rs#189]
Sorry that I'm very new to Rust. Are newer versions on crate.io just new builds based on the same source code of lazy-static?

**Comment by eaon** [comment]
It doesn't: https://github.com/rust-lang-nursery/lazy-static.rs/releases

1.1.1 is maintenance/bugfix release for an older version. See https://github.com/rust-lang-nursery/lazy-static.rs/pull/162

**Comment by dclong** [comment]
Thank you for the clarification!
