### ISSUE TITLE
Add a check to make sure statics only have sized type

### ISSUE THREAD

**Issue by Kimundi** [rust-lang-nursery/lazy-static.rs#26]

**Comment by Kimundi** [comment]
This is implicitly given by the structure of the code now, but hard to write a test for since it would have to be a compile-fail test.

**Comment by yvt** [comment]
`rustdoc` has [the `compile_fail` doctest attribute](https://doc.rust-lang.org/nightly/rustdoc/documentation-tests.html#attributes) for compile-fail tests. Does this solve the issue?

**Comment by Kimundi** [comment]
I was think more of a regular compile_fail test, but this would work too.
