### ISSUE TITLE
unreachable intrinsic

### ISSUE THREAD

**Issue by durka** [rust-lang-nursery/lazy-static.rs#33]
The library depends on the `core_intrinsics` feature in order to use `std::intrinsics::unreachable`. Is this considered fine, or should we consider an alternative such as depending on [@reem's unreachable](https://github.com/reem/rust-unreachable) or using a local zero-variant enum?

**Comment by Kimundi** [comment]
I think as long the lib depends on other unstable features in the conditional code where unreachable is used its a moot point. 

If this should become the only thing blocking stable though then it should be easy to switch to one of those alternatives.

**Comment by durka** [comment]
Sounds good.
