### ISSUE TITLE
#![no_std] support

### ISSUE THREAD

**Issue by lilred** [rust-lang-nursery/lazy-static.rs#35]
It would be lovely if this crate supported `#![no_std]`. The documentation doesn't mention anything about it though.

This request is two-fold:

1. Please update the documentation to mention whether this crate supports `#![no_std]`, and whether it plans on supporting it.
2. Please implement support for `#![no_std]` :)

**Comment by Amanieu** [comment]
I don't think that supporting `!#[no_std]` is feasible since the code relies on `std::sync::Once` to prevent concurrent initialization. In the end you need some sort of mutex, which is outside the scope of libcore since it is inherently platform-specific.

**Comment by Ryman** [comment]
I think this can be closed now as it's implemented in https://github.com/rust-lang-nursery/lazy-static.rs/pull/46. You can use [this feature](https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/Cargo.toml#L20).

**Comment by Kimundi** [comment]
Indeed!
