### ISSUE TITLE
Document that cyclic dependencies cause deadlock

### ISSUE THREAD

**Issue by ciphergoth** [rust-lang-nursery/lazy-static.rs#37]
A cycle in the evaluation of lazy_statics will cause deadlock when one is evaluated.  I tested this by adding `m.insert(*COUNT as u32, "deadlock");` to the hashmap in the sample program. This makes perfect sense, but seems worth adding to the documentation.

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

I'll add a sentence about this to the docs.

**Comment by Kimundi** [comment]
Done, should be reflected in the docs as soon as the doc builds finish.

**Comment by ciphergoth** [comment]
That's great, thank you so much, and please don't feel the need to apologise - I'm grateful for all the work you do on Rust!
