### ISSUE TITLE
Should be possible to use within deny(unsafe_code)

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang-nursery/lazy-static.rs#38]

**Comment by Kimundi** [comment]
In the sense of "this macro represents a safe abstraction, and as such should not be able to trigger the lint"?

Adding `#[allow(unsafe_code)]` to it should do the trick, hm... But I guess we can not do the equivalent of making it work with `#[forbid(unsafe_code)]`, right?

**Comment by Ms2ger** [comment]
Exactly.

**Comment by Kimundi** [comment]
Alright, this got addressed in v0.2!
