### ISSUE TITLE
Mutability support

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang-nursery/lazy-static.rs#39]
Any way to support DerefMut?

**Comment by Kimundi** [comment]
Lazy statics behave like regular statics in the sense of only allowing shared, `&T` access to a value. If you want mutability you need to put your values behind a `Mutex`, for example:

```rust
lazy_static! {
    static ref X: Mutex<u32> = Mutex::new(0);
}

fn main() {
    *X.lock() = 100;
}
```

**Comment by SethDusek** [comment]
Yes but regular statics allow mutability though. Shouldn't lazy_static also allow mutable statics?
