### ISSUE TITLE
A feature for spinning and core-only

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang-nursery/lazy-static.rs#44]
This would be useful freestanding work.

I actually wrote this in my fork of this library already (as a change, not optional feature), but I moved the lazy implementation to https://github.com/mvdnes/spinlock-rs/blob/master/src/once.rs and would pull that as an (optional) dependency.

**Comment by Kimundi** [comment]
Just for reference: The spinlock would be needed for no_std since locking primitives in std are OS/plattform specific and do not exist in libcore?

**Comment by Ericson2314** [comment]
Yeah, exactly. I supposed I should rename the feature as most "std" or "no_std" features don't change any algorithms but just work around stability.

**Comment by Kimundi** [comment]
Yeah, maybe just something like `spinlock_no_std`

**Comment by Ericson2314** [comment]
Ok done. The repo stayed the same, but the library was renamed `spin`, so I called the feature "spin_no_std"
