### ISSUE TITLE
Relicense under BSL-1.0

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang-nursery/lazy-static.rs#47]
Hi, can the project be relicensed under BSL-1.0?

> MIT/Apache-2 has issues where MIT is permissive and all but you always need to include the license, and Apache-2 is not so permissive and you need to always include the license AND a NOTICE file if any.
>
> BSL only needs the license for source distribution, you can remove the license for compiled code. For most software this would be a downside, but for things like Anymap, my event system (`eventbus` I believe it's called), or something that provides mostly basic macros and things like that (e.g. in the C++ world, boost itself), BSL may be a better choice.
>
> This is, of course, a matter of opinion, but I sincerely would like to be able to use this project in BSL-licensed projects without having to make my users include the license.

(This is related to the current version of `eventbus`, my BSL-licensed event library, requiring `lazy-static` for creating eventbuses and events)

**Comment by Kimundi** [comment]
Hi, this library is intended to have the same licensing scheme as the Rust std library, so unless they change the licenses as well I probably won't do this, sorry :)
