### ISSUE TITLE
Cannot use tuples

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang-nursery/lazy-static.rs#51]
Unless I just have the syntax wrong? I've tried both:

`static (ref x, ref y): (u8, u8) = (5u8, 6u8);`
`static ref (x, y): (u8, u8) = (5u8, 6u8);`

**Comment by chpio** [comment]
the `(x, y)` should be name, i guess.

> For a given `static ref NAME: TYPE = EXPR;`, the macro generates a unique type that implements Deref<TYPE> and stores it in a static with name NAME.

**Comment by evanmcc** [comment]
I could also use this.

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

lazy static mirrors the syntax of Rusts regular `static`s, which do not allow pattern matching either. As such, I do not plan to add this feature, sorry. :)
