### ISSUE TITLE
lazy_static 0.2.1 on crates.io contains a ~2MB liblib.so file

### ISSUE THREAD

**Issue by staktrace** [rust-lang-nursery/lazy-static.rs#54]
I believe the currently published lazy_static crate on crates.io (version 0.2.1) contains a giant .so file inside which was probably included by accident. As part of putting webrender into gecko we did the equivalent of `cargo vendor` on webrender, which pulls down all the dependencies' source recursively. The source for lazy_static includes this .so file, even though it's not it in the lazy_static git repo.

You can also see that between version 0.1.9 and 0.2.0 the file size jumped dramatically, by comparing the size of `wget https://crates.io/api/v1/crates/lazy_static/0.1.9/download` and `wget https://crates.io/api/v1/crates/lazy_static/0.2.0/download` so I assume that's when it appeared.

Could you please publish an updated crate to crates.io which doesn't contain this monster file? Thanks!

**Comment by Kimundi** [comment]
I'll investigate

**Comment by Kimundi** [comment]
The Issue should be fixed now.

**Comment by staktrace** [comment]
Verified as fixed, thanks!
