### ISSUE TITLE
A method for forcing the initialization of the value other than just deref?

### ISSUE THREAD

**Issue by golddranks** [rust-lang-nursery/lazy-static.rs#58]
I'm using lazy static with an initializer that might fail runtime (checking an env var and panicking if it's not set up correctly). I want to ensure that the values are set up early in my application: either it should work or error at startup. To this end, I dereference my lazy statics as a part of my init routine.

However, I recently run Clippy on my code, and it complains about this:

    warning: statement with no effect, #[warn(no_effect)] on by default
       --> src/helpers.rs:325:5
        |
    325 |     &*DATABASE_URL;
        |     ^^^^^^^^^^^^^^^
        |
        = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#no_effect

Indeed, a plain deref doesn't even communicate the intent properly (the derefs are wrapped in function whose name communicates it, but that's irrelevant here). Would it make sense to have a method that forces the initialization, for communicating the intent?

**Comment by golddranks** [comment]
Forgot to mention: there is a workaround for silencing Clippy (other than `allow`): `let _ = &* DATABASE_URL;`

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

Seems like a reasonable thing to add, I'll experiment a bit.

**Comment by Kimundi** [comment]
[I added a function for this in the new release](http://rust-lang-nursery.github.io/lazy-static.rs/lazy_static/fn.initialize.html).
