### ISSUE TITLE
Approaches to get a destructor when `main` finishes.

### ISSUE THREAD

**Issue by dpc** [rust-lang-nursery/lazy-static.rs#62]
Hi, I have a problem that I wish I could rely somehow on destruction of `lazy_static` to call drop on what's inside it. I know it might be impossible, but I guess it's worth asking. Suggestions for workaround etc. are welcome. I was eg. thinking about using a `Weak` inside `lazy_static`, but then I do have to have a strong reference somewhere in the main thread.

**Comment by Kimundi** [comment]
Rust as a language has basically made the design decision to not have custom user code running before or after `main()`, so if a static variable contains a type with a destructor, that destructor will just never be called. As far as I'm aware, there is no good way to have a automatic destruction anyway, so lazy_static just mirrors that semantic.

However, the crate could provide something like `lazy_static::destroy()` for manually destroying a static. The issue there is just that the internally used `std::Once` has no way to be "reset", so someone who is more knowledgeable about thread synchronisation primitives than I would have to write a custom implementation for that (which would also be useful for #60).

**Comment by Kimundi** [comment]
One possible workaround you could do is to have the lazy_static be of a `Mutex<Option<T>>` or similar, and then destroy the `T` by overwriting the `Option` with a `None`

**Comment by dpc** [comment]
For synchronization I'm quite sure to resort to `ArcCell` from `crossbeam` or what you have mentioned.

**Comment by KodrAus** [comment]
It's been a while now, so I'll go ahead and close this issue as a design decision we inherit from Rust upstream. Please feel free to re-open though if there's anything more you'd like to add!

**Comment by jtmoon79** [comment]
FYI this affects crate [`tempfile`](https://github.com/Stebalien/tempfile/issues/183).
