### ISSUE TITLE
Publish CI badges for all Tier 1 platforms

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/lazy-static.rs#65]
Per https://github.com/brson/rust-api-guidelines#c-ci.

**Comment by brson** [comment]
Looks like lazy_static only has Linux CI set up, so we'll also need to add an os x config, and appveyor.

**Comment by brson** [comment]
We're probably going to remove this from the guidelines pending better support in cargo for specifying exactly what's being tested, so maybe we should just close?

**Comment by KodrAus** [comment]
I think this is worth doing, personally. We need to land #74 first though.
