### ISSUE TITLE
Include `homepage` in Cargo.toml

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/lazy-static.rs#67]
Although there is a debate to be had about whether this is necessary... https://github.com/brson/rust-api-guidelines/issues/26.

**Comment by neosilky** [comment]
Would like to work on this. Should we use https://github.com/rust-lang-nursery/lazy-static.rs or https://crates.io/crates/lazy_static as the homepage?

**Comment by dtolnay** [comment]
We don't know :confused: https://github.com/brson/rust-api-guidelines/issues/26. I think this will be discussed at the libs team meeting next week.

**Comment by neosilky** [comment]
Alright, I'll keep an eye on the meeting and see what they say :grinning:

**Comment by tmccombs** [comment]
Alternatively, there could be an actual homepage for lazy_static.

**Comment by brson** [comment]
Resolution on the guidelines is to not add 'homepage' unless there is an actual homepage.
