### ISSUE TITLE
Compilation failure on nightly

### ISSUE THREAD

**Issue by joshlf** [rust-lang-nursery/lazy-static.rs#85]
As of `rustc 1.22.0-nightly (cfcac3720 2017-09-17)`, lazy-static fails to build on nightly due to [this issue in `spin`](https://github.com/mvdnes/spin-rs/issues/43).

**Comment by KodrAus** [comment]
We've also got some changes in #85 related to splitting the `const_fn` cfg.

**Comment by joshlf** [comment]
Gotcha.
