### ISSUE TITLE
please add minimum Rust version to CI

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/lazy-static.rs#92]
I'd like to know what the minimum support Rust version if for `lazy_static`. I'm not necessarily asking for any particular policy with respect to semver, but just knowing that lazy_static works on Rust 1.x is incredibly useful information.

**Comment by KodrAus** [comment]
Looks like `lazy_static` works at least as far back as `1.11.0` before the compiler stopped working on my machine so I guess we just need to pick a version and include it in CI. `1.15.1`? `1.20.0`?

**Comment by KodrAus** [comment]
https://github.com/rust-lang-nursery/lazy-static.rs/commit/c0fbc23aa9924eba2c134745f0a353bb97c08d23 added `1.21.0` as the minimum supported version, so I think we can go ahead and close this one now.
