### ISSUE TITLE
[Meta] Using github releases

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang-nursery/lazy-static.rs#94]
Hey

It will be nice if the maintainers update the [releases](https://github.com/rust-lang-nursery/lazy-static.rs/releases) every time a new version is released perhaps with a changelog. Makes it easier for users using this crate. If needed, would love to contribute that on every release 

Keep up the good work 👍  😃

**Comment by KodrAus** [comment]
Thanks @Dylan-DPC! I've created a tag for the latest `1.0.1` release and I think we should keep on top of them going forward so I think we can close this one now.
